// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using _12.Week_Code_First_1.Data;

#nullable disable

namespace _12.Week_Code_First_1.Data.Migrations
{
    [DbContext(typeof(PatikaFirstDbContext))]
    [Migration("20241218160227_Ilk")]
    partial class Ilk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("_12.Week_Code_First_1.Data.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(20,2)");

                    b.HasKey("Id");

                    b.ToTable("Games", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Elden Ring",
                            Platform = "PC",
                            Rating = 0m
                        },
                        new
                        {
                            Id = 2,
                            Name = "God of War: Ragnarok",
                            Platform = "PlayStation",
                            Rating = 0m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Forza Horizon 5",
                            Platform = "Xbox",
                            Rating = 0m
                        },
                        new
                        {
                            Id = 4,
                            Name = "The Legend of Zelda: Breath of the Wild",
                            Platform = "Nintendo Switch",
                            Rating = 0m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Hogwarts Legacy",
                            Platform = "PC",
                            Rating = 0m
                        });
                });

            modelBuilder.Entity("_12.Week_Code_First_1.Data.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Movies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = "Science Fiction",
                            ReleaseYear = 2014,
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = 2,
                            Genre = "Thriller",
                            ReleaseYear = 2019,
                            Title = "Parasite"
                        },
                        new
                        {
                            Id = 3,
                            Genre = "Action",
                            ReleaseYear = 2015,
                            Title = "Mad Max: Fury Road"
                        },
                        new
                        {
                            Id = 4,
                            Genre = "Drama",
                            ReleaseYear = 1994,
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            Id = 5,
                            Genre = "Animation",
                            ReleaseYear = 2001,
                            Title = "Spirited Away"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
